/** Based on https://stackoverflow.com/questions/15722765/saving-a-text-file-on-server-using-javascript
 * See also https://www.php.net/manual/en/reserved.variables.post.php:
 * - The comments in tool.js:writeSave() before `xhr.send(data)` explain that
 *   the content type is multipart/form-data, as required.
 * Note also browser version requirements to use FormData:
 * - https://developer.mozilla.org/en-US/docs/Web/API/FormData#browser_compatibility
 */
 
/**
Saves both English and Georgian time-syllables files.
Assumes syllables were validated when they were uploaded.
*/
<?php
include_once "georgian_english.php";
debug_to_console("[save_time_syllables.php]");

if (!empty($_POST['data'])) {
	$saveData = test_input($_POST['data']);
    $language = $_POST['language'];
	$savePathEn = "georgian/data/syllables/" . htmlspecialchars($_POST['path']) . "_time_syllables_en.txt";
	$savePathGe = "georgian/data/syllables/" . htmlspecialchars($_POST['path']) . "_time_syllables_ge.txt";
}
if ($language == "en") {
    $saveDataEn = $saveData;
    $saveDataGe = en2ge($saveData);
} else {
    $saveDataGe = $saveData;
    $saveDataEn = ge2en($saveData);
}

$saveFile = fopen($savePathEn, 'w');
if ($saveFile === false) {
   debug_to_console("opening '" . $saveFile . "' failed");
   exit;
}
fwrite($saveFile, $saveDataEn);
debug_to_console("Wrote save file " . $saveFile);
fclose($saveFile);

$saveFile = fopen($savePathGe, 'w');
if ($saveFile === false) {
   debug_to_console("opening '" . $saveFile . "' failed");
   exit;
}
fwrite($saveFile, $saveDataGe);
debug_to_console("Wrote save file " . $saveFile);
fclose($saveFile);

/*!! I don't see the need for this. We want to preserve apostrophes.
 *   All the content was generated by the app after the original upload of the syllable file.
 */
function test_input($data) {
	$data = stripslashes($data);
	//$data = htmlspecialchars($data);
	return $data;
}

function debug_to_console($data) {
    $output = $data;
    if (is_array($output))
        $output = implode(',', $output);

    echo "<script>console.log('PHP Debug: " . $output . "' );</script>";
}

?>
